MANTA-848 need global zone log rotation for marlin (cont)

diff --git a/tools/mragentconf b/tools/mragentconf
--- a/tools/mragentconf
+++ b/tools/mragentconf
@@ -98,13 +98,17 @@ echo "wrote logpush.json"
 
 # Add the log rotator to the crontab.
 mac_tmpfile=/var/tmp/$mac_arg0.$$
-crontab -l | grep -v $mac_confdir/logpush.json > $mac_tmpfile || \
-    fail "failed to save old crontab"
-echo "1,2,3,4,5 * * * * $mac_root/sbin/logpush.sh $mac_confdir/logpush.json " \
-    ">> /var/log/mbackup.log 2>&1" >> $mac_tmpfile || fail "failed to append"
-crontab $mac_tmpfile || fail "failed to load $mac_tmpfile"
-rm -f $mac_tmpfile
-echo "updated crontab"
+if ! crontab -l | grep logpush.json > /dev/null; then
+	echo "1,2,3,4,5 * * * * $mac_root/sbin/logpush.sh " \
+	    "$mac_confdir/logpush.json >> " \
+	    "/var/log/mbackup.log 2>&1" >> $mac_tmpfile || \
+	    fail "failed to append"
+	crontab $mac_tmpfile || fail "failed to load $mac_tmpfile"
+	rm -f $mac_tmpfile
+	echo "updated crontab"
+else
+	echo "skipping crontab update (already done)"
+fi
 
 # Update logadm.conf to rotate the Marlin agent log before the other SMF logs.
 logadm -r marlin-agent
