MANTA-1445 want log rotation for per-job debug streams

diff --git a/tools/mragentconf b/tools/mragentconf
--- a/tools/mragentconf
+++ b/tools/mragentconf
@@ -96,13 +96,17 @@ cat > $mac_confdir/logpush.json <<EOF || fail "failed to write logpush.json"
 EOF
 echo "wrote logpush.json"
 
-# Add the log rotator to the crontab.
+# Add the log rotator entries to the crontab.
 mac_tmpfile=/var/tmp/$mac_arg0.$$
-if ! crontab -l | grep logpush.json > /dev/null; then
+if ! crontab -l | grep logpush.json > /dev/null ||
+   ! crontab -l | grep mrlogexpire > /dev/null; then
 	echo "1,2,3,4,5 * * * * $mac_root/sbin/logpush.sh " \
 	    "$mac_confdir/logpush.json >> " \
-	    "/var/log/mbackup.log 2>&1" >> $mac_tmpfile || \
+	    "/var/log/mbackup.log 2>&1" > $mac_tmpfile || \
 	    fail "failed to append"
+	echo "0 0 * * * $mac_root/sbin/mrlogexpire.sh " \
+	    ">> /var/log/mrlogexpire.log 2>&1" >> $mac_tmpfile ||
+	    fail "failed to append (2)"
 	crontab $mac_tmpfile || fail "failed to load $mac_tmpfile"
 	rm -f $mac_tmpfile
 	echo "updated crontab"
