MANTA-804 tag marlin compute zones with a ZFS property

diff --git a/tools/mrzoneremove b/tools/mrzoneremove
--- a/tools/mrzoneremove
+++ b/tools/mrzoneremove
@@ -86,3 +86,7 @@ echo "done."
 echo -n "Removing zone \"$mr_zonename\" ... \c "
 zone_remove $mr_zonename || fail "failed"
 echo "done."
+
+echo -n "Removing com.joyent.manta:marlin property ... \c "
+zfs inherit com.joyent.manta:marlin zones/$mr_zonename || fail "failed"
+echo "done."
